"use client";

/**
 * /app/auth/confirm/page.tsx
 *
 * Supabase delivers auth tokens in two completely different formats:
 *
 * FORMAT A — token_hash in QUERY PARAMS
 *   Generated by: supabase.auth.resetPasswordForEmail() (forgotPasswordAction)
 *   URL: /auth/confirm?token_hash=pkce_xxx&type=recovery
 *   Handler: supabase.auth.verifyOtp({ token_hash, type: EmailOtpType })
 *
 * FORMAT B — tokens in URL FRAGMENT (#)
 *   Generated by: supabase.auth.admin.generateLink() (admitStudentAction)
 *   URL: /auth/confirm#access_token=xxx&refresh_token=yyy&type=recovery
 *   Handler: supabase.auth.setSession({ access_token, refresh_token })
 *   NOTE: Servers can NEVER read fragments — MUST be a client component.
 *
 * After either succeeds → /auth/reset-password
 */

import { createBrowserClient } from "@supabase/ssr";
import type { EmailOtpType } from "@supabase/supabase-js";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { GraduationCap } from "lucide-react";

// Valid values for token_hash-based verifyOtp (email flows only — no SMS)
const EMAIL_OTP_TYPES: EmailOtpType[] = [
  "recovery",
  "signup",
  "invite",
  "magiclink",
  "email",
  "email_change",
];

function isEmailOtpType(value: string): value is EmailOtpType {
  return EMAIL_OTP_TYPES.includes(value as EmailOtpType);
}

export default function AuthConfirmPage() {
  const router = useRouter();
  const [status, setStatus] = useState<"loading" | "error">("loading");
  const [errorMessage, setErrorMessage] = useState("");

  useEffect(() => {
    const supabase = createBrowserClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    );

    async function handleAuth() {
      // Clear any stale session (e.g. admin who clicked a parent invite link)
      await supabase.auth.signOut();

      const searchParams = new URLSearchParams(window.location.search);
      const hashParams = new URLSearchParams(window.location.hash.slice(1));

      // Check for Supabase error in either location first
      const errorDesc =
        searchParams.get("error_description") ??
        hashParams.get("error_description");

      if (errorDesc) {
        setErrorMessage(decodeURIComponent(errorDesc.replace(/\+/g, " ")));
        setStatus("error");
        return;
      }

      // ── FORMAT A: token_hash in query string ───────────────────────────
      // Produced by resetPasswordForEmail() → forgotPasswordAction
      const tokenHash = searchParams.get("token_hash");
      const type = searchParams.get("type");

      if (tokenHash && type) {
        if (!isEmailOtpType(type)) {
          setErrorMessage(
            `Unsupported link type: "${type}". Please contact the school office.`,
          );
          setStatus("error");
          return;
        }

        const { error } = await supabase.auth.verifyOtp({
          token_hash: tokenHash,
          type, // now correctly typed as EmailOtpType
        });

        if (error) {
          setErrorMessage(buildErrorMessage(error.message));
          setStatus("error");
          return;
        }

        router.replace("/auth/reset-password");
        return;
      }

      // ── FORMAT B: tokens in URL fragment ──────────────────────────────
      // Produced by admin.generateLink({ type: "recovery" }) → admitStudentAction
      const accessToken = hashParams.get("access_token");
      const refreshToken = hashParams.get("refresh_token");
      const hashType = hashParams.get("type");

      if (accessToken && refreshToken) {
        const { error } = await supabase.auth.setSession({
          access_token: accessToken,
          refresh_token: refreshToken,
        });

        if (error) {
          setErrorMessage(buildErrorMessage(error.message));
          setStatus("error");
          return;
        }

        router.replace(
          hashType === "recovery" ? "/auth/reset-password" : "/admin/dashboard",
        );
        return;
      }

      // Neither format matched — already used or malformed
      setErrorMessage(
        "This link has already been used or is no longer valid. Each setup link can only be clicked once.",
      );
      setStatus("error");
    }

    handleAuth();
  }, [router]);

  // ── Error screen ────────────────────────────────────────────────────────────

  if (status === "error") {
    return (
      <div className="min-h-screen bg-[#0c0f1a] flex items-center justify-center p-6">
        <div className="pointer-events-none fixed inset-0 overflow-hidden">
          <div className="absolute -top-40 left-1/2 -translate-x-1/2 w-[600px] h-[600px] rounded-full bg-rose-500/5 blur-[120px]" />
        </div>

        <div className="relative w-full max-w-md text-center">
          <div className="flex justify-center mb-6">
            <div className="flex h-9 w-9 items-center justify-center rounded-xl bg-amber-400/10 border border-amber-400/20">
              <GraduationCap className="h-4 w-4 text-amber-400" />
            </div>
          </div>

          <div className="rounded-2xl border border-white/[0.08] bg-white/[0.04] backdrop-blur-xl shadow-2xl shadow-black/40 overflow-hidden">
            <div className="h-px w-full bg-gradient-to-r from-transparent via-rose-400/40 to-transparent" />
            <div className="p-8 space-y-5">
              <div className="flex justify-center">
                <div className="flex h-14 w-14 items-center justify-center rounded-full bg-rose-500/10 border border-rose-500/20">
                  <svg
                    className="h-7 w-7 text-rose-400"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={1.5}
                      d="M12 9v2m0 4h.01M12 3a9 9 0 100 18A9 9 0 0012 3z"
                    />
                  </svg>
                </div>
              </div>

              <div>
                <h2 className="text-lg font-bold text-white mb-2">
                  Link Unavailable
                </h2>
                <p className="text-sm text-white/50 leading-relaxed">
                  {errorMessage}
                </p>
              </div>

              <div className="rounded-xl border border-white/[0.06] bg-white/[0.03] px-4 py-3 text-left">
                <p className="text-[11px] font-semibold text-white/40 uppercase tracking-wider mb-1">
                  Need a new link?
                </p>
                <p className="text-xs text-white/30 leading-relaxed">
                  Request a fresh reset link below, or visit the school office
                  and a staff member can reset your account in person.
                </p>
              </div>

              <div className="flex flex-col gap-2 pt-1">
                <a
                  href="/auth/forgot-password"
                  className="w-full rounded-xl bg-amber-400 py-2.5 text-sm font-bold text-[#0c0f1a] hover:bg-amber-300 transition-colors"
                >
                  Request a New Link
                </a>
                <a
                  href="/login"
                  className="w-full rounded-xl border border-white/10 py-2.5 text-sm font-semibold text-white/50 hover:text-white/80 hover:border-white/20 transition-colors"
                >
                  Back to Login
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    );
  }

  // ── Loading screen ────────────────────────────────────────────────────────────

  return (
    <div className="min-h-screen bg-[#0c0f1a] flex flex-col items-center justify-center gap-6">
      <div className="pointer-events-none fixed inset-0 overflow-hidden">
        <div className="absolute -top-40 left-1/2 -translate-x-1/2 w-[600px] h-[600px] rounded-full bg-amber-500/5 blur-[120px]" />
      </div>
      <style>{`
        @keyframes ka-spin { to { transform: rotate(360deg); } }
        .ka-spin { animation: ka-spin 0.9s linear infinite; }
      `}</style>
      <div className="flex h-9 w-9 items-center justify-center rounded-xl bg-amber-400/10 border border-amber-400/20">
        <GraduationCap className="h-4 w-4 text-amber-400" />
      </div>
      <div className="flex flex-col items-center gap-3">
        <div className="w-10 h-10 rounded-full border-[3px] border-amber-400/20 border-t-amber-400 ka-spin" />
        <p className="text-white font-semibold">Verifying your link…</p>
        <p className="text-white/30 text-sm">
          Redirecting you to set your password.
        </p>
      </div>
    </div>
  );
}

function buildErrorMessage(raw: string): string {
  const msg = raw.toLowerCase();
  if (msg.includes("expired") || msg.includes("invalid"))
    return "This link has expired or has already been used. Setup links are valid for 24 hours — please request a new one.";
  if (msg.includes("otp"))
    return "The verification code in this link is no longer valid. Please request a fresh link.";
  return `Verification failed: ${raw}`;
}
