// lib/types/allocation.ts

export type SubjectLevel =
  | "lower_primary"
  | "upper_primary"
  | "junior_secondary";

export interface Class {
  id: string;
  school_id: string; // Multi-tenant scope context
  grade: string;
  stream: string;
  level: SubjectLevel;
  academic_year: number; 
  created_at?: string;
}

export interface Subject {
  id: string;
  school_id: string; // Multi-tenant scope context
  name: string;
  code: string;
  level: SubjectLevel;
  weekly_lessons: number;
  created_at: string;
}

export interface TeacherSubjectAllocation {
  id: string;
  school_id: string; // Multi-tenant scope context
  teacher_id: string;
  subject_id: string;
  class_id: string; 
  academic_year: number;
  is_active: boolean;
  created_at: string;
  
  // ── Corrected Joined Data Relations ────────────────────────────────────────
  teachers: {
    id: string;
    staff_id: string | null;
    tsc_number: string | null;
    profiles: {
      full_name: string;
    } | null; // Profile reference mapping logic fix
  } | null;
  subjects: {
    id: string;
    name: string;
    code: string;
    level: SubjectLevel;
    weekly_lessons: number;
  } | null;
  classes: Class | null; 
}

export interface TimetableSlot {
  id: string;
  school_id: string; // Multi-tenant scope context
  allocation_id: string;
  grade: string; // Dynamic tracking label generated by scheduling loops
  day_of_week: number; // 1–5
  period: number; // 1–8
  academic_year: number;
  created_at: string;
  
  // ── Corrected Joined Data Relations ────────────────────────────────────────
  teacher_subject_allocations: {
    class_id: string;
    teachers: { 
      id: string; 
      profiles: { full_name: string } | null;
    } | null;
    subjects: { name: string; code: string } | null;
    classes: Class | null; 
  } | null;
}

// ── UI timetable cell ─────────────────────────────────────────────────────────

export interface TimetableCell {
  slotId: string;
  teacherName: string;
  subjectName: string;
  subjectCode: string;
  allocationId: string;
  teacherId: string;
  className: string; 
}

// Keyed by `${day}-${period}`
export type TimetableGrid = Record<string, TimetableCell | null>;

export interface AllocationFormValues {
  teacherId: string;
  subjectId: string;
  classId: string; 
  academicYear: number;
}

// ── Constants & Helpers ───────────────────────────────────────────────────────

export const CBC_LEVEL_LABELS: Record<SubjectLevel, string> = {
  lower_primary: "Lower Primary (PP1 - Grade 3)",
  upper_primary: "Upper Primary (Grade 4 - Grade 6)",
  junior_secondary: "Junior Secondary (Grade 7 - Grade 9)",
};

export const DAYS = [
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
] as const;
export type Day = (typeof DAYS)[number];

export const PERIODS = [1, 2, 3, 4, 5, 6, 7, 8] as const;
export type Period = (typeof PERIODS)[number];

export const PERIOD_TIMES: Record<number, string> = {
  1: "7:30–8:20",
  2: "8:20–9:10",
  3: "9:10–10:00",
  4: "10:20–11:10",
  5: "11:10–12:00",
  6: "12:00–12:50",
  7: "1:30–2:20",
  8: "2:20–3:10",
};

/**
 * Helper to format the class display name consistently across the app.
 * Usage: formatClassName(allocation.classes) -> "Grade 4 South"
 */
export const formatClassName = (classObj: Class | null | undefined): string => {
  if (!classObj) return "Unknown Class";
  if (classObj.stream === "Main") return classObj.grade;
  return `${classObj.grade} ${classObj.stream}`;
};